# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f39323466d9336e4f7617e8de761f2fb827da265f36a7dc9a74eb61a2b8643ca540c604ba8445e430031fb3a2965bba13662a28cf6ceb356910ecc9327345a

test:
  secret_key_base: 620a9c427fb0489b55f3c8ffc5e80f76ddf6304966a27b74f780d1b2d1a399e56b37307e899c7a39dec501ba5aba1f241d97ac02cef3e60687fe67f76eab00d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
